version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      tanstack:
        patterns:
          - '@tanstack/*'
      sentry:
        patterns:
          - '@sentry/*'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
