packages:
  - 'apps/*'

# Ensure platform-specific optional dependencies are installed for CI (Linux)
supportedArchitectures:
  os:
    - linux
    - darwin
    - current
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
